import SwiftUI

// 支持的语言
enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case simplifiedChinese = "zh-Hans"
    case traditionalChinese = "zh-Hant"
    case japanese = "ja"
    case korean = "ko"
    case spanish = "es"
    
    var id: String { rawValue }
    
    var displayName: String {
        switch self {
        case .english: return "English"
        case .simplifiedChinese: return "简体中文"
        case .traditionalChinese: return "繁體中文"
        case .japanese: return "日本語"
        case .korean: return "한국어"
        case .spanish: return "Español"
        }
    }
    
    var flag: String {
        switch self {
        case .english: return "🇺🇸"
        case .simplifiedChinese: return "🇨🇳"
        case .traditionalChinese: return "🇭🇰"
        case .japanese: return "🇯🇵"
        case .korean: return "🇰🇷"
        case .spanish: return "🇪🇸"
        }
    }
}

// 语言管理器
class LanguageManager: ObservableObject {
    @Published var currentLanguage: AppLanguage {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "appLanguage")
        }
    }
    
    static let shared = LanguageManager()
    
    private init() {
        let savedLanguage = UserDefaults.standard.string(forKey: "appLanguage") ?? "en"
        self.currentLanguage = AppLanguage(rawValue: savedLanguage) ?? .english
    }
    
    // 获取本地化文本
    func localizedString(_ key: String) -> String {
        return LocalizedStrings.getString(key, language: currentLanguage)
    }
}

// 本地化字符串
struct LocalizedStrings {
    static func getString(_ key: String, language: AppLanguage) -> String {
        let strings = allStrings[language] ?? allStrings[.english]!
        return strings[key] ?? key
    }

    static let allStrings: [AppLanguage: [String: String]] = [
        .simplifiedChinese: [
            "app_title": "你比划我猜",
            "upgrade_to_pro": "升级VIP",
            "pro_activated": "专业版已激活",
            "create_category": "创建类型",
            "read_privacy": "阅读隐私政策",
            "game_rules": "游戏规则",
            "game_rules_content": "1. 选择分类和时间开始游戏\n2. 一人比划一人猜，比划者不能说出题目中的字\n3. 猜对点击✓按钮得1分，不会可点击跳过\n4. 时间结束后显示总得分",
            "i_know": "我知道了",
            "select_time": "选择游戏时长",
            "start_game": "开始游戏",
            "correct": "答对",
            "skip": "跳过",
            "exit_game": "退出游戏",
            "confirm_exit": "确认退出",
            "game_in_progress": "游戏正在进行中，确定要退出吗？",
            "cancel": "取消",
            "exit": "退出",
            "game_over": "时间到！",
            "total_score": "答对总数：%d 个",
            "total_score_label": "答对总数",
            "back_to_home": "返回首页",
            "pro_version": "专业版",
            "locked": "🔒",
            "custom": "自定义",
            "privacy_policy_title": "隐私政策",
            "privacy_last_updated": "最后更新日期：2026年2月22日",
            "privacy_summary_title": "简要说明",
            "privacy_summary_content": "本应用不收集、存储或分享任何个人信息。应用完全离线运行，所有数据仅存储在您的设备本地。",
            "privacy_section_1_title": "1. 信息收集",
            "privacy_section_1_content": "「你比划我猜」是一款完全离线的聚会游戏应用。我们不收集、存储或传输任何个人信息，包括但不限于：\n• 个人身份信息（姓名、邮箱、电话等）\n• 设备信息\n• 位置信息\n• 使用数据\n• 游戏记录",
            "privacy_section_2_title": "2. 数据存储",
            "privacy_section_2_content": "应用的所有功能均在您的设备本地运行：\n• 游戏数据仅在游戏进行时临时存储在设备内存中\n• 游戏结束后，所有数据自动清除\n• 不会在设备上创建任何持久化存储\n• 不会将任何数据上传到服务器",
            "privacy_section_3_title": "3. 第三方服务",
            "privacy_section_3_content": "本应用不使用任何第三方服务，包括：\n• 分析服务（如 Google Analytics）\n• 广告服务\n• 社交媒体集成\n• 云存储服务",
            "privacy_section_4_title": "4. 网络连接",
            "privacy_section_4_content": "本应用完全离线运行，不需要网络连接。应用不会：\n• 访问互联网\n• 发送或接收任何数据\n• 连接到任何服务器",
            "privacy_section_5_title": "5. 儿童隐私",
            "privacy_section_5_content": "本应用适合所有年龄段使用（4+）。由于我们不收集任何信息，因此不会收集儿童的个人信息。",
            "privacy_section_6_title": "6. 权限说明",
            "privacy_section_6_content": "本应用不请求任何系统权限，包括：\n• 相机\n• 麦克风\n• 位置\n• 通讯录\n• 照片\n• 网络访问",
            "privacy_section_7_title": "7. 数据安全",
            "privacy_section_7_content": "由于本应用不收集或传输任何数据，因此不存在数据泄露的风险。所有游戏内容均在您的设备本地运行。",
            "privacy_copyright": "© 2026 你比划我猜. 保留所有权利。",
            "edit_cards_hint": "长按自己创建的卡片可以进行编辑和删除",
            "enjoy_title": "享受",
            "premium_features": "专业版功能",
            "unlock_all_categories": "解锁所有游戏分类",
            "premium_word_library": "700+ 精选词汇库",
            "create_custom_categories": "创建自定义分类",
            "ad_free_experience": "无广告纯净体验",
            "cross_platform_support": "支持 iPhone 和 iPad",
            "cancel_anytime": "随时可以取消订阅",
            "weekly": "周订阅",
            "monthly": "月订阅",
            "yearly": "年订阅",
            "best_value": "最超值",
            "most_popular": "最受欢迎",
            "free_trial": "免费试用",
            "then_per_week": "然后每周",
            "then_per_month": "然后每月",
            "then_per_year": "然后每年",
            "subscribe_now": "立即订阅",
            "restore_purchases": "恢复购买",
            "terms_and_privacy": "订阅条款和隐私政策",
            "choose_your_plan": "选择您的计划",
            "lifetime": "终身版",
            "one_time": "一次性付费",
            "save_58_percent": "✦ 比月订阅节省58%",
            "only_monthly_cost": "✦ 仅需 **$1.67/月**",
            "pay_once_own_forever": "✦ 一次付费，永久拥有",
            "premium_unlock": "专业版解锁",
            "what_you_get": "您将获得：",
            "all_categories_unlocked": "解锁所有分类",
            "no_ads": "无广告",
            "custom_words_categories": "自定义词汇和分类",
            "free_lifetime_updates": "免费终身更新",
            "terms_apply": "购买确认后将从您的iTunes账户扣费。订阅将自动续费，除非在当前订阅期结束前至少24小时取消。",
            "privacy_policy": "隐私政策",
            "terms_of_use": "使用条款",
            "terms_of_use_title": "使用条款",
            "terms_last_updated": "最后更新日期：2026年2月22日",
            "terms_section_1_title": "1. 条款接受",
            "terms_section_1_content": "通过下载、安装或使用你比划我猜，您同意受本使用条款的约束。如果您不同意这些条款，请不要使用本应用。",
            "terms_section_2_title": "2. 服务描述",
            "terms_section_2_content": "你比划我猜是一款提供词汇分类的聚会游戏应用，用于娱乐目的。应用通过订阅提供免费和付费内容。",
            "terms_section_3_title": "3. 订阅条款",
            "terms_section_3_content": "专业版订阅提供额外的游戏分类。订阅将自动续费，除非在当前订阅期结束前至少24小时取消。购买确认后将从您的iTunes账户扣费。",
            "terms_section_4_title": "4. 用户行为",
            "terms_section_4_content": "您同意仅将应用用于合法目的并遵守本条款。您不得以任何可能损害、禁用或损坏应用的方式使用应用。",
            "terms_section_5_title": "5. 知识产权",
            "terms_section_5_content": "应用中的所有内容，包括但不限于文本、图形、标识和软件，均为你比划我猜的财产，受版权和其他知识产权法保护。",
            "terms_section_6_title": "6. 责任限制",
            "terms_section_6_content": "你比划我猜不对因您使用应用而产生的任何间接、偶然、特殊或后果性损害承担责任。",
            "terms_section_7_title": "7. 联系信息",
            "terms_section_7_content": "如果您对本使用条款有任何疑问，请通过seventiny007@126.com联系我们。",
            "terms_copyright": "© 2026 你比划我猜. 保留所有权利。",
            "restore": "恢复",
            "3_day_free_trial": "3天免费试用",
            "one_time_pay": "一次性付费",
            "new_category": "新建",
            "save": "保存",
            "category_name": "分类名称",
            "category_name_placeholder": "例如：水果、动物、品牌等",
            "input_words": "输入词汇",
            "input_words_hint": "用逗号或换行分隔，至少输入5个词汇",
            "select_icon": "选择封面图标",
            "creation_success": "创建成功",
            "edit_cards_hint_ipad": "长按可以编辑自己创建的卡片"
        ],
        .traditionalChinese: [
            "app_title": "你比劃我猜",
            "upgrade_to_pro": "升級VIP",
            "pro_activated": "專業版已激活",
            "create_category": "創建類型",
            "read_privacy": "閱讀隱私政策",
            "game_rules": "遊戲規則",
            "game_rules_content": "1. 選擇分類和時間開始遊戲\n2. 一人比劃一人猜，比劃者不能說出題目中的字\n3. 猜對點擊✓按鈕得1分，不會可點擊跳過\n4. 時間結束後顯示總得分",
            "i_know": "我知道了",
            "select_time": "選擇遊戲時長",
            "start_game": "開始遊戲",
            "correct": "答對",
            "skip": "跳過",
            "exit_game": "退出遊戲",
            "confirm_exit": "確認退出",
            "game_in_progress": "遊戲正在進行中，確定要退出嗎？",
            "cancel": "取消",
            "exit": "退出",
            "game_over": "時間到！",
            "total_score": "答對總數：%d 個",
            "total_score_label": "答對總數",
            "back_to_home": "返回首頁",
            "pro_version": "專業版",
            "locked": "🔒",
            "custom": "自定義",
            "privacy_policy_title": "隱私政策",
            "privacy_last_updated": "最後更新日期：2026年2月22日",
            "privacy_summary_title": "簡要說明",
            "privacy_summary_content": "本應用不收集、存儲或分享任何個人信息。應用完全離線運行，所有數據僅存儲在您的設備本地。",
            "privacy_section_1_title": "1. 信息收集",
            "privacy_section_1_content": "「你比劃我猜」是一款完全離線的聚會遊戲應用。我們不收集、存儲或傳輸任何個人信息，包括但不限於：\n• 個人身份信息（姓名、郵箱、電話等）\n• 設備信息\n• 位置信息\n• 使用數據\n• 遊戲記錄",
            "privacy_section_2_title": "2. 數據存儲",
            "privacy_section_2_content": "應用的所有功能均在您的設備本地運行：\n• 遊戲數據僅在遊戲進行時臨時存儲在設備內存中\n• 遊戲結束後，所有數據自動清除\n• 不會在設備上創建任何持久化存儲\n• 不會將任何數據上傳到服務器",
            "privacy_section_3_title": "3. 第三方服務",
            "privacy_section_3_content": "本應用不使用任何第三方服務，包括：\n• 分析服務（如 Google Analytics）\n• 廣告服務\n• 社交媒體集成\n• 雲存儲服務",
            "privacy_section_4_title": "4. 網絡連接",
            "privacy_section_4_content": "本應用完全離線運行，不需要網絡連接。應用不會：\n• 訪問互聯網\n• 發送或接收任何數據\n• 連接到任何服務器",
            "privacy_section_5_title": "5. 兒童隱私",
            "privacy_section_5_content": "本應用適合所有年齡段使用（4+）。由於我們不收集任何信息，因此不會收集兒童的個人信息。",
            "privacy_section_6_title": "6. 權限說明",
            "privacy_section_6_content": "本應用不請求任何系統權限，包括：\n• 相機\n• 麥克風\n• 位置\n• 通訊錄\n• 照片\n• 網絡訪問",
            "privacy_section_7_title": "7. 數據安全",
            "privacy_section_7_content": "由於本應用不收集或傳輸任何數據，因此不存在數據洩露的風險。所有遊戲內容均在您的設備本地運行。",
            "privacy_copyright": "© 2026 你比劃我猜. 保留所有權利。",
            "edit_cards_hint": "長按自己創建的卡片可以進行編輯和刪除",
            "enjoy_title": "享受",
            "premium_features": "專業版功能",
            "unlock_all_categories": "解鎖所有遊戲分類",
            "premium_word_library": "700+ 精選詞彙庫",
            "create_custom_categories": "創建自定義分類",
            "ad_free_experience": "無廣告純淨體驗",
            "cross_platform_support": "支持 iPhone 和 iPad",
            "cancel_anytime": "隨時可以取消訂閱",
            "weekly": "週訂閱",
            "monthly": "月訂閱",
            "yearly": "年訂閱",
            "best_value": "最超值",
            "most_popular": "最受歡迎",
            "free_trial": "免費試用",
            "then_per_week": "然後每週",
            "then_per_month": "然後每月",
            "then_per_year": "然後每年",
            "subscribe_now": "立即訂閱",
            "restore_purchases": "恢復購買",
            "terms_and_privacy": "訂閱條款和隱私政策",
            "choose_your_plan": "選擇您的計劃",
            "lifetime": "終身版",
            "one_time": "一次性付費",
            "save_58_percent": "✦ 比月訂閱節省58%",
            "only_monthly_cost": "✦ 僅需 **$1.67/月**",
            "pay_once_own_forever": "✦ 一次付費，永久擁有",
            "premium_unlock": "專業版解鎖",
            "what_you_get": "您將獲得：",
            "all_categories_unlocked": "解鎖所有分類",
            "no_ads": "無廣告",
            "custom_words_categories": "自定義詞彙和分類",
            "free_lifetime_updates": "免費終身更新",
            "terms_apply": "條款適用。訂閱將自動續費，除非取消。",
            "privacy_policy": "隱私政策",
            "terms_of_use": "使用條款",
            "restore": "恢復",
            "3_day_free_trial": "3天免費試用",
            "one_time_pay": "一次性付費",
            "new_category": "新建",
            "save": "保存",
            "category_name": "分類名稱",
            "category_name_placeholder": "例如：水果、動物、品牌等",
            "input_words": "輸入詞彙",
            "input_words_hint": "用逗號或換行分隔，至少輸入5個詞彙",
            "select_icon": "選擇封面圖標",
            "creation_success": "創建成功",
            "edit_cards_hint_ipad": "長按可以編輯自己創建的卡片"
        ],
        .english: [
            "app_title": "GuessMe",
            "upgrade_to_pro": "Upgrade VIP",
            "pro_activated": "Pro Activated",
            "create_category": "Create Category",
            "read_privacy": "Privacy Policy",
            "game_rules": "Game Rules",
            "game_rules_content": "1. Select category and time to start\n2. One person acts, one guesses\n3. Tap ✓ for correct, skip if needed\n4. View score when time's up",
            "i_know": "Got it",
            "select_time": "Select Game Duration",
            "start_game": "Start Game",
            "correct": "Correct",
            "skip": "Skip",
            "exit_game": "Exit Game",
            "confirm_exit": "Confirm Exit",
            "game_in_progress": "Game in progress. Exit now?",
            "cancel": "Cancel",
            "exit": "Exit",
            "game_over": "Time's Up!",
            "total_score": "Total Score: %d",
            "total_score_label": "Total Score",
            "back_to_home": "Back to Home",
            "pro_version": "Pro",
            "locked": "🔒",
            "custom": "Custom",
            "privacy_policy_title": "Privacy Policy",
            "privacy_last_updated": "Last Updated: February 22, 2026",
            "privacy_summary_title": "Summary",
            "privacy_summary_content": "This app does not collect, store, or share any personal information. The app runs completely offline, and all data is stored locally on your device.",
            "privacy_section_1_title": "1. Information Collection",
            "privacy_section_1_content": "\"GuessMe\" is a completely offline party game app. We do not collect, store, or transmit any personal information, including but not limited to:\n• Personal identification information (name, email, phone, etc.)\n• Device information\n• Location information\n• Usage data\n• Game records",
            "privacy_section_2_title": "2. Data Storage",
            "privacy_section_2_content": "All app functions run locally on your device:\n• Game data is temporarily stored in device memory only during gameplay\n• All data is automatically cleared after the game ends\n• No persistent storage is created on the device\n• No data is uploaded to any server",
            "privacy_section_3_title": "3. Third-Party Services",
            "privacy_section_3_content": "This app does not use any third-party services, including:\n• Analytics services (such as Google Analytics)\n• Advertising services\n• Social media integration\n• Cloud storage services",
            "privacy_section_4_title": "4. Network Connection",
            "privacy_section_4_content": "This app runs completely offline and does not require an internet connection. The app will not:\n• Access the internet\n• Send or receive any data\n• Connect to any server",
            "privacy_section_5_title": "5. Children's Privacy",
            "privacy_section_5_content": "This app is suitable for all ages (4+). Since we do not collect any information, we do not collect personal information from children.",
            "privacy_section_6_title": "6. Permissions",
            "privacy_section_6_content": "This app does not request any system permissions, including:\n• Camera\n• Microphone\n• Location\n• Contacts\n• Photos\n• Network access",
            "privacy_section_7_title": "7. Data Security",
            "privacy_section_7_content": "Since this app does not collect or transmit any data, there is no risk of data breach. All game content runs locally on your device.",
            "privacy_copyright": "© 2026 GuessMe. All rights reserved.",
            "edit_cards_hint": "Long press your custom cards to edit and delete",
            "enjoy_title": "ENJOY",
            "premium_features": "Premium Features",
            "unlock_all_categories": "Unlock all game categories",
            "premium_word_library": "700+ premium word library",
            "create_custom_categories": "Create custom categories",
            "ad_free_experience": "Ad-free pure experience",
            "cross_platform_support": "iPhone and iPad support",
            "cancel_anytime": "Cancel subscription anytime",
            "weekly": "Weekly",
            "monthly": "Monthly",
            "yearly": "Yearly",
            "best_value": "BEST VALUE",
            "most_popular": "MOST POPULAR",
            "free_trial": "Free Trial",
            "then_per_week": "then per week",
            "then_per_month": "then per month",
            "then_per_year": "then per year",
            "subscribe_now": "Subscribe Now",
            "restore_purchases": "Restore Purchases",
            "terms_and_privacy": "Terms and Privacy Policy",
            "choose_your_plan": "Choose Your Plan",
            "lifetime": "Lifetime",
            "one_time": "ONE-TIME",
            "save_58_percent": "✦ Save 58% vs monthly",
            "only_monthly_cost": "✦ Only **$1.67/month**",
            "pay_once_own_forever": "✦ Pay once, own forever",
            "premium_unlock": "Premium Unlock",
            "what_you_get": "What You Get:",
            "all_categories_unlocked": "All categories unlocked",
            "no_ads": "No ads",
            "custom_words_categories": "Custom words & categories",
            "free_lifetime_updates": "Free lifetime updates",
            "terms_apply": "Payment will be charged to your iTunes account at confirmation of purchase. Subscription automatically renews unless canceled at least 24 hours before the end of the current period.",
            "privacy_policy": "Privacy Policy",
            "terms_of_use": "Terms of Use",
            "terms_of_use_title": "Terms of Use",
            "terms_last_updated": "Last Updated: February 22, 2026",
            "terms_section_1_title": "1. Acceptance of Terms",
            "terms_section_1_content": "By downloading, installing, or using GuessMe, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the app.",
            "terms_section_2_title": "2. Description of Service",
            "terms_section_2_content": "GuessMe is a charades game app that provides word categories for entertainment purposes. The app offers both free and premium content through subscription.",
            "terms_section_3_title": "3. Subscription Terms",
            "terms_section_3_content": "Premium subscriptions provide access to additional game categories. Subscriptions automatically renew unless canceled at least 24 hours before the end of the current period. Payment will be charged to your iTunes account at confirmation of purchase.",
            "terms_section_4_title": "4. User Conduct",
            "terms_section_4_content": "You agree to use the app only for lawful purposes and in accordance with these Terms. You may not use the app in any way that could damage, disable, or impair the app.",
            "terms_section_5_title": "5. Intellectual Property",
            "terms_section_5_content": "All content in the app, including but not limited to text, graphics, logos, and software, is the property of GuessMe and is protected by copyright and other intellectual property laws.",
            "terms_section_6_title": "6. Limitation of Liability",
            "terms_section_6_content": "GuessMe shall not be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the app.",
            "terms_section_7_title": "7. Contact Information",
            "terms_section_7_content": "If you have any questions about these Terms of Use, please contact us at seventiny007@126.com",
            "terms_copyright": "© 2026 GuessMe. All rights reserved.",
            "restore": "Restore",
            "3_day_free_trial": "3-day free trial",
            "one_time_pay": "ONE-TIME PAY",
            "new_category": "New",
            "save": "Save",
            "category_name": "Category Name",
            "category_name_placeholder": "e.g.: Fruits, Animals, Brands",
            "input_words": "Input Words",
            "input_words_hint": "Separate with commas or line breaks, at least 5 words",
            "select_icon": "Select Cover Icon",
            "creation_success": "Created Successfully",
            "edit_cards_hint_ipad": "Long press to edit your created cards"
        ],
        .japanese: [
            "app_title": "ジェスチャーゲーム",
            "upgrade_to_pro": "VIPにアップグレード",
            "pro_activated": "プロ版有効",
            "create_category": "カテゴリを作成",
            "read_privacy": "プライバシーポリシー",
            "game_rules": "ゲームルール",
            "game_rules_content": "1. カテゴリと時間を選択\n2. 一人がジェスチャー、一人が当てる\n3. 正解は✓、スキップも可能\n4. 時間終了後にスコア表示",
            "i_know": "了解",
            "select_time": "ゲーム時間を選択",
            "start_game": "ゲーム開始",
            "correct": "正解",
            "skip": "スキップ",
            "exit_game": "ゲーム終了",
            "confirm_exit": "終了確認",
            "game_in_progress": "ゲーム進行中です。終了しますか？",
            "cancel": "キャンセル",
            "exit": "終了",
            "game_over": "時間切れ！",
            "total_score": "正解数：%d 個",
            "total_score_label": "正解数",
            "back_to_home": "ホームに戻る",
            "pro_version": "プロ版",
            "locked": "🔒",
            "custom": "カスタム",
            "privacy_policy_title": "プライバシーポリシー",
            "privacy_last_updated": "最終更新日：2026年2月22日",
            "privacy_summary_title": "概要",
            "privacy_summary_content": "このアプリは個人情報を収集、保存、または共有しません。アプリは完全にオフラインで実行され、すべてのデータはデバイスにローカルに保存されます。",
            "privacy_section_1_title": "1. 情報収集",
            "privacy_section_1_content": "「ジェスチャーゲーム」は完全にオフラインで実行されるパーティーゲームアプリです。以下を含む個人情報は収集、保存、または送信されません：\n• 個人識別情報（名前、メール、電話など）\n• デバイス情報\n• 位置情報\n• 使用データ\n• ゲーム記録",
            "privacy_section_2_title": "2. データ保存",
            "privacy_section_2_content": "すべてのアプリ機能はデバイスでローカルに実行されます：\n• ゲームデータはゲーム中のみデバイスメモリに一時的に保存されます\n• ゲーム終了後、すべてのデータは自動的に削除されます\n• デバイスに永続的なストレージは作成されません\n• サーバーにデータはアップロードされません",
            "privacy_section_3_title": "3. 第三者サービス",
            "privacy_section_3_content": "このアプリは第三者サービスを使用しません：\n• 分析サービス（Google Analyticsなど）\n• 広告サービス\n• ソーシャルメディア統合\n• クラウドストレージサービス",
            "privacy_section_4_title": "4. ネットワーク接続",
            "privacy_section_4_content": "このアプリは完全にオフラインで実行され、インターネット接続は不要です。アプリは以下を行いません：\n• インターネットにアクセス\n• データを送受信\n• サーバーに接続",
            "privacy_section_5_title": "5. 子どものプライバシー",
            "privacy_section_5_content": "このアプリはすべての年齢層に適しています（4+）。情報を収集しないため、子どもの個人情報は収集されません。",
            "privacy_section_6_title": "6. 権限",
            "privacy_section_6_content": "このアプリはシステム権限をリクエストしません：\n• カメラ\n• マイク\n• 位置情報\n• 連絡先\n• 写真\n• ネットワークアクセス",
            "privacy_section_7_title": "7. データセキュリティ",
            "privacy_section_7_content": "このアプリはデータを収集または送信しないため、データ漏洩のリスクはありません。すべてのゲームコンテンツはデバイスでローカルに実行されます。",
            "privacy_copyright": "© 2026 ジェスチャーゲーム. すべての権利を保有します。",
            "edit_cards_hint": "自分で作成したカードを長押しすると編集・削除できます",
            "enjoy_title": "楽しむ",
            "premium_features": "プレミアム機能",
            "unlock_all_categories": "すべてのゲームカテゴリを解除",
            "premium_word_library": "700+ プレミアム単語ライブラリ",
            "create_custom_categories": "カスタムカテゴリを作成",
            "ad_free_experience": "広告なしの純粋な体験",
            "cross_platform_support": "iPhone と iPad サポート",
            "cancel_anytime": "いつでもサブスクリプションをキャンセル",
            "weekly": "週間",
            "monthly": "月間",
            "yearly": "年間",
            "best_value": "最高の価値",
            "most_popular": "最も人気",
            "free_trial": "無料トライアル",
            "then_per_week": "その後週あたり",
            "then_per_month": "その後月あたり",
            "then_per_year": "その後年あたり",
            "subscribe_now": "今すぐ購読",
            "restore_purchases": "購入を復元",
            "terms_and_privacy": "利用規約とプライバシーポリシー",
            "choose_your_plan": "プランを選択",
            "lifetime": "ライフタイム",
            "one_time": "一回限り",
            "save_58_percent": "✦ 月額より58%節約",
            "only_monthly_cost": "✦ わずか **$1.67/月**",
            "pay_once_own_forever": "✦ 一度支払えば永久に所有",
            "premium_unlock": "プレミアム解除",
            "what_you_get": "取得内容：",
            "all_categories_unlocked": "すべてのカテゴリを解除",
            "no_ads": "広告なし",
            "custom_words_categories": "カスタム単語とカテゴリ",
            "free_lifetime_updates": "無料終身アップデート",
            "terms_apply": "利用規約が適用されます。キャンセルしない限り、サブスクリプションは自動更新されます。",
            "privacy_policy": "プライバシーポリシー",
            "terms_of_use": "利用規約",
            "restore": "復元",
            "3_day_free_trial": "3日間無料トライアル",
            "one_time_pay": "一回限り",
            "new_category": "新規",
            "save": "保存",
            "category_name": "カテゴリ名",
            "category_name_placeholder": "例：果物、動物、ブランド",
            "input_words": "単語を入力",
            "input_words_hint": "カンマまたは改行で区切り、最低5個の単語",
            "select_icon": "カバーアイコンを選択",
            "creation_success": "作成成功",
            "edit_cards_hint_ipad": "長押しで作成したカードを編集できます"
        ],
        .korean: [
            "app_title": "몸으로 말해요",
            "upgrade_to_pro": "VIP 업그레이드",
            "pro_activated": "프로 활성화됨",
            "create_category": "카테고리 만들기",
            "read_privacy": "개인정보 보호정책",
            "game_rules": "게임 규칙",
            "game_rules_content": "1. 카테고리와 시간 선택\n2. 한 사람은 몸짓, 한 사람은 맞추기\n3. 정답은 ✓, 건너뛰기 가능\n4. 시간 종료 후 점수 확인",
            "i_know": "알겠습니다",
            "select_time": "게임 시간 선택",
            "start_game": "게임 시작",
            "correct": "정답",
            "skip": "건너뛰기",
            "exit_game": "게임 종료",
            "confirm_exit": "종료 확인",
            "game_in_progress": "게임이 진행 중입니다. 종료하시겠습니까?",
            "cancel": "취소",
            "exit": "종료",
            "game_over": "시간 종료!",
            "total_score": "총 점수: %d 개",
            "total_score_label": "총 점수",
            "back_to_home": "홈으로 돌아가기",
            "pro_version": "프로",
            "locked": "🔒",
            "custom": "커스텀",
            "privacy_policy_title": "개인정보 보호정책",
            "privacy_last_updated": "마지막 업데이트: 2026년 2월 22일",
            "privacy_summary_title": "요약",
            "privacy_summary_content": "이 앱은 개인정보를 수집, 저장 또는 공유하지 않습니다. 앱은 완전히 오프라인으로 실행되며 모든 데이터는 기기에 로컬로 저장됩니다.",
            "privacy_section_1_title": "1. 정보 수집",
            "privacy_section_1_content": "\"몸으로 말해요\"는 완전히 오프라인으로 실행되는 파티 게임 앱입니다. 다음을 포함한 개인정보는 수집, 저장 또는 전송되지 않습니다:\n• 개인 식별 정보(이름, 이메일, 전화 등)\n• 기기 정보\n• 위치 정보\n• 사용 데이터\n• 게임 기록",
            "privacy_section_2_title": "2. 데이터 저장",
            "privacy_section_2_content": "모든 앱 기능은 기기에서 로컬로 실행됩니다:\n• 게임 데이터는 게임 중에만 기기 메모리에 임시로 저장됩니다\n• 게임 종료 후 모든 데이터는 자동으로 삭제됩니다\n• 기기에 영구 저장소가 생성되지 않습니다\n• 서버에 데이터가 업로드되지 않습니다",
            "privacy_section_3_title": "3. 제3자 서비스",
            "privacy_section_3_content": "이 앱은 제3자 서비스를 사용하지 않습니다:\n• 분석 서비스(Google Analytics 등)\n• 광고 서비스\n• 소셜 미디어 통합\n• 클라우드 저장소 서비스",
            "privacy_section_4_title": "4. 네트워크 연결",
            "privacy_section_4_content": "이 앱은 완전히 오프라인으로 실행되며 인터넷 연결이 필요하지 않습니다. 앱은 다음을 수행하지 않습니다:\n• 인터넷 접근\n• 데이터 송수신\n• 서버 연결",
            "privacy_section_5_title": "5. 아동 개인정보",
            "privacy_section_5_content": "이 앱은 모든 연령대에 적합합니다(4+). 정보를 수집하지 않으므로 아동의 개인정보는 수집되지 않습니다.",
            "privacy_section_6_title": "6. 권한",
            "privacy_section_6_content": "이 앱은 시스템 권한을 요청하지 않습니다:\n• 카메라\n• 마이크\n• 위치\n• 연락처\n• 사진\n• 네트워크 접근",
            "privacy_section_7_title": "7. 데이터 보안",
            "privacy_section_7_content": "이 앱은 데이터를 수집하거나 전송하지 않으므로 데이터 유출 위험이 없습니다. 모든 게임 콘텐츠는 기기에서 로컬로 실행됩니다.",
            "privacy_copyright": "© 2026 몸으로 말해요. 모든 권리 보유.",
            "edit_cards_hint": "자신이 만든 카드를 길게 누르면 편집과 삭제가 가능합니다",
            "enjoy_title": "즐기기",
            "premium_features": "프리미엄 기능",
            "unlock_all_categories": "모든 게임 카테고리 잠금 해제",
            "premium_word_library": "700+ 프리미엄 단어 라이브러리",
            "create_custom_categories": "커스텀 카테고리 생성",
            "ad_free_experience": "광고 없는 순수한 경험",
            "cross_platform_support": "iPhone 및 iPad 지원",
            "cancel_anytime": "언제든지 구독 취소",
            "weekly": "주간",
            "monthly": "월간",
            "yearly": "연간",
            "best_value": "최고 가치",
            "most_popular": "가장 인기",
            "free_trial": "무료 체험",
            "then_per_week": "그 다음 주당",
            "then_per_month": "그 다음 월당",
            "then_per_year": "그 다음 연당",
            "subscribe_now": "지금 구독",
            "restore_purchases": "구매 복원",
            "terms_and_privacy": "약관 및 개인정보 보호정책",
            "choose_your_plan": "플랜 선택",
            "lifetime": "평생",
            "one_time": "일회성",
            "save_58_percent": "✦ 월간 대비 58% 절약",
            "only_monthly_cost": "✦ 단지 **$1.67/월**",
            "pay_once_own_forever": "✦ 한 번 결제로 영구 소유",
            "premium_unlock": "프리미엄 잠금 해제",
            "what_you_get": "얻을 수 있는 것:",
            "all_categories_unlocked": "모든 카테고리 잠금 해제",
            "no_ads": "광고 없음",
            "custom_words_categories": "커스텀 단어 및 카테고리",
            "free_lifetime_updates": "무료 평생 업데이트",
            "terms_apply": "약관이 적용됩니다. 취소하지 않는 한 구독이 자동으로 갱신됩니다.",
            "privacy_policy": "개인정보 보호정책",
            "terms_of_use": "이용약관",
            "restore": "복원",
            "3_day_free_trial": "3일 무료 체험",
            "one_time_pay": "일회성",
            "new_category": "새로 만들기",
            "save": "저장",
            "category_name": "카테고리 이름",
            "category_name_placeholder": "예: 과일, 동물, 브랜드",
            "input_words": "단어 입력",
            "input_words_hint": "쉼표나 줄바꿈으로 구분, 최소 5개 단어",
            "select_icon": "커버 아이콘 선택",
            "creation_success": "생성 완료",
            "edit_cards_hint_ipad": "길게 눌러서 만든 카드를 편집할 수 있습니다"
        ],
        .spanish: [
            "app_title": "Adivina el Gesto",
            "upgrade_to_pro": "Actualizar VIP",
            "pro_activated": "Pro Activado",
            "create_category": "Crear Categoría",
            "read_privacy": "Política de Privacidad",
            "game_rules": "Reglas del Juego",
            "game_rules_content": "1. Selecciona categoría y tiempo\n2. Una persona actúa, otra adivina\n3. Toca ✓ si es correcto, salta si no\n4. Ver puntuación al terminar",
            "i_know": "Entendido",
            "select_time": "Seleccionar Duración",
            "start_game": "Iniciar Juego",
            "correct": "Correcto",
            "skip": "Saltar",
            "exit_game": "Salir del Juego",
            "confirm_exit": "Confirmar Salida",
            "game_in_progress": "Juego en progreso. ¿Salir ahora?",
            "cancel": "Cancelar",
            "exit": "Salir",
            "game_over": "¡Tiempo!",
            "total_score": "Puntuación Total: %d",
            "total_score_label": "Puntuación Total",
            "back_to_home": "Volver al Inicio",
            "pro_version": "Pro",
            "locked": "🔒",
            "custom": "Personalizado",
            "privacy_policy_title": "Política de Privacidad",
            "privacy_last_updated": "Última actualización: 22 de febrero de 2026",
            "privacy_summary_title": "Resumen",
            "privacy_summary_content": "Esta aplicación no recopila, almacena ni comparte información personal. La aplicación se ejecuta completamente sin conexión y todos los datos se almacenan localmente en su dispositivo.",
            "privacy_section_1_title": "1. Recopilación de Información",
            "privacy_section_1_content": "\"Adivina el Gesto\" es una aplicación de juego de fiesta completamente sin conexión. No recopilamos, almacenamos ni transmitimos información personal, incluyendo pero no limitado a:\n• Información de identificación personal (nombre, correo electrónico, teléfono, etc.)\n• Información del dispositivo\n• Información de ubicación\n• Datos de uso\n• Registros de juego",
            "privacy_section_2_title": "2. Almacenamiento de Datos",
            "privacy_section_2_content": "Todas las funciones de la aplicación se ejecutan localmente en su dispositivo:\n• Los datos del juego se almacenan temporalmente en la memoria del dispositivo solo durante el juego\n• Todos los datos se eliminan automáticamente después de que termina el juego\n• No se crea almacenamiento persistente en el dispositivo\n• No se carga ningún dato en ningún servidor",
            "privacy_section_3_title": "3. Servicios de Terceros",
            "privacy_section_3_content": "Esta aplicación no utiliza servicios de terceros:\n• Servicios de análisis (como Google Analytics)\n• Servicios de publicidad\n• Integración de redes sociales\n• Servicios de almacenamiento en la nube",
            "privacy_section_4_title": "4. Conexión de Red",
            "privacy_section_4_content": "Esta aplicación se ejecuta completamente sin conexión y no requiere conexión a Internet. La aplicación no:\n• Accede a Internet\n• Envía o recibe datos\n• Se conecta a ningún servidor",
            "privacy_section_5_title": "5. Privacidad de Menores",
            "privacy_section_5_content": "Esta aplicación es adecuada para todas las edades (4+). Como no recopilamos información, no recopilamos información personal de menores.",
            "privacy_section_6_title": "6. Permisos",
            "privacy_section_6_content": "Esta aplicación no solicita permisos del sistema:\n• Cámara\n• Micrófono\n• Ubicación\n• Contactos\n• Fotos\n• Acceso a la red",
            "privacy_section_7_title": "7. Seguridad de Datos",
            "privacy_section_7_content": "Como esta aplicación no recopila ni transmite datos, no hay riesgo de violación de datos. Todo el contenido del juego se ejecuta localmente en su dispositivo.",
            "privacy_copyright": "© 2026 Adivina el Gesto. Todos los derechos reservados.",
            "edit_cards_hint": "Mantén presionadas las tarjetas que creaste para editarlas y eliminarlas",
            "enjoy_title": "DISFRUTA",
            "premium_features": "Características Premium",
            "unlock_all_categories": "Desbloquear todas las categorías de juego",
            "premium_word_library": "700+ biblioteca de palabras premium",
            "create_custom_categories": "Crear categorías personalizadas",
            "ad_free_experience": "Experiencia pura sin anuncios",
            "cross_platform_support": "Soporte para iPhone e iPad",
            "cancel_anytime": "Cancelar suscripción en cualquier momento",
            "weekly": "Semanal",
            "monthly": "Mensual",
            "yearly": "Anual",
            "best_value": "MEJOR VALOR",
            "most_popular": "MÁS POPULAR",
            "free_trial": "Prueba Gratuita",
            "then_per_week": "luego por semana",
            "then_per_month": "luego por mes",
            "then_per_year": "luego por año",
            "subscribe_now": "Suscribirse Ahora",
            "restore_purchases": "Restaurar Compras",
            "terms_and_privacy": "Términos y Política de Privacidad",
            "choose_your_plan": "Elige Tu Plan",
            "lifetime": "De por vida",
            "one_time": "UNA VEZ",
            "save_58_percent": "✦ Ahorra 58% vs mensual",
            "only_monthly_cost": "✦ Solo **$1.67/mes**",
            "pay_once_own_forever": "✦ Paga una vez, posee para siempre",
            "premium_unlock": "Desbloqueo Premium",
            "what_you_get": "Lo que obtienes:",
            "all_categories_unlocked": "Todas las categorías desbloqueadas",
            "no_ads": "Sin anuncios",
            "custom_words_categories": "Palabras y categorías personalizadas",
            "free_lifetime_updates": "Actualizaciones gratuitas de por vida",
            "terms_apply": "Se aplican términos. La suscripción se renueva automáticamente a menos que se cancele.",
            "privacy_policy": "Política de Privacidad",
            "terms_of_use": "Términos de Uso",
            "restore": "Restaurar",
            "3_day_free_trial": "3 días de prueba gratuita",
            "one_time_pay": "UNA VEZ",
            "new_category": "Nuevo",
            "save": "Guardar",
            "category_name": "Nombre de Categoría",
            "category_name_placeholder": "ej.: Frutas, Animales, Marcas",
            "input_words": "Ingresar Palabras",
            "input_words_hint": "Separar con comas o saltos de línea, mínimo 5 palabras",
            "select_icon": "Seleccionar Ícono de Portada",
            "creation_success": "Creado Exitosamente",
            "edit_cards_hint_ipad": "Mantén presionado para editar las tarjetas que creaste"
        ]
    ]
}
